Indexdb
cse110-fa22-group18/cse110-fa22-group18 pull request #45
Opened 2022-12-02 04:46 UTC by dangeo314

## Workload Includes
1. Changed all local storage aspects to indexedDB.

## Tests Done
1. Manual testing of upload, delete, download, edit/save.

## Potential Improvements
1. More testing

2022-12-03 02:45 UTC, nkarter02 commented on source/assets/scripts/database.mjs
> +export async function openDb() {
going to need js doc commenting

2022-12-03 02:46 UTC, nkarter02 commented on source/assets/scripts/database.mjs
> +        request.onsuccess = (event) => {
yeah definitely going to need comments since idk whats going on

2022-12-03 02:48 UTC, nkarter02 requested changes
pretty much just needs comments, variable naming and code styling is good

2022-12-04 21:11 UTC, mchera24 reviewed
Looks good

2022-12-04 21:28 UTC, nkarter02 approved these changes

2022-12-04 21:34 UTC, merged